TELEGRAM_BOT_TOKEN="<telegram_token>"
TELEGRAM_CHAT_ID="telegram_chat_id"

# aplikace, které chceš hlídat
APPS=("immich" "jdownloader2" "jellyfin" "joplin" "linkwarden" "mb-it-web" "mc-tekkit" "minecraft" "n8n" "nextcloud" "nginx-proxy-manager" "rust-desk" "stash")

# kolik sekund čekat po startu/update
START_WAIT=600

# log
LOG_FILE="/mnt/Apps/Scripts/logs/truenas-watchdog.log"
